#!/bin/bash

echo "### create rke service account ###"
sleep 1
useradd -m -g docker rke
mkdir -p /home/rke/.ssh
chmod 700 /home/rke/.ssh
chmod -R go= /home/rke/.ssh

echo "### create and copy ssh keys for rke user ###"
HOME=/root
cd ${HOME}
echo "HOME [$HOME]"
echo "PWD [$PWD]"
sleep 1
(cat /dev/zero | ssh-keygen -q -N "") 1>/dev/null 2>/dev/null
echo "SSH-KEYGEN FINISHED"
cat /root/.ssh/id_rsa.pub
\cp /root/.ssh/id_rsa.pub /home/rke/.ssh/authorized_keys
chown -R rke:docker /home/rke
ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" rke@localhost << EOT
	docker version
EOT

echo "### install rke cli ###"
sleep 1
curl -Lo /usr/bin/rke https://github.com/rancher/rke/releases/download/v1.2.3/rke_linux-amd64
#https://github.com/rancher/rke/releases/latest
chmod +x /usr/bin/rke
rke --version

echo "### install kubectl cli ###"
sleep 1
KUBERELEASE=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
curl -Lo /usr/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/${KUBERELEASE}/bin/linux/amd64/kubectl"
chmod +x /usr/bin/kubectl
kubectl version --client

echo "### initialise rke cluster ###"
sleep 1
cat << EOF > /root/rke.config.yaml
ignore_docker_version: true
nodes:
  - address: localhost
    user: rke
    role:
      - controlplane
      - etcd
      - worker
ingress:
  provider: none
monitoring:
  provider: none
network:
  plugin: calico
EOF
rke up --config /root/rke.config.yaml --ignore-docker-version

echo "### sync kubeconfig ###"
sleep 1
mkdir -p /root/.kube
cp kube_config_rke.config.yaml /root/.kube/config

echo "### rke/install complete ###"
