---
apiVersion: v1
kind: Service
metadata:
  name: vip-doom
  namespace: kubedoom
  annotations:
    metallb.universe.tf/allow-shared-ip: host
spec:
  selector:
    app: kubedoom
  ports:
    - port: 5900
      targetPort: 5900
  type: LoadBalancer

