{
	"air_worth_date": "19540430",
	"airborne": false,
	"cert_issue_date": "20050506",
	"certification": "1         ",
	"city": "KETCHUM           ",
	"country": "US",
	"county": "097",
	"eng_mfr_mdl": "17003",
	"expiration_date": "20230430",
	"fract_owner": " ",
	"kit_mfr": "                              ",
	"kit_model": "                    ",
	"last_action_date": "20200105",
	"mfr_mdl_code": "7100510",
	"mode_s_code": "50002263",
	"mode_s_code_hex": "A004B3    ",
	"n_number": "100  ",
	"name": "BENE MARY D                                       ",
	"other_names_1": "                                                  ",
	"other_names_2": "                                                  ",
	"other_names_3": "                                                  ",
	"other_names_4": "                                                  ",
	"other_names_5": "                                                  ",
	"planedetails": {
		"ac_cat": "1",
		"ac_weight": "CLASS 1",
		"build_cert_ind": "0",
		"code": "7100510",
		"mfr": "PIPER                         ",
		"model": "J3C-65              ",
		"no_eng": "01",
		"no_setas": "002",
		"speed": "0067",
		"tp_acft": "4",
		"tp_eng": "1 "
	},
	"serial_number": "5334                          ",
	"state": "OK",
	"status_code": "V ",
	"street": "PO BOX 329                       ",
	"street2": "                                 ",
	"tp_aircraft": "4",
	"tp_engine": "1 ",
	"type_registrant": "1",
	"unique_id": "00600060",
	"year_mfr": "1940",
	"zip_code": "743490329 "
}
