apiVersion: v1
kind: Service
metadata:
  name: vip-frontend
  labels:
    app.kubernetes.io/instance: sockshop-all-in-one
    name: front-end
  annotations:
    metallb.universe.tf/allow-shared-ip: host
spec:
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
  type: LoadBalancer
