#!/bin/bash
## module: k3s/install
## purpose: install the k3s server and place a kubeconfig at /root/.kube/config
## inputs:  K3S_DISABLE (comma list of bundled components to disable; default servicelb,traefik)
## needs:   -

## must run as root; restore /usr/local/bin in PATH (RHEL sudo strips it)
[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "must be run as root" >&2; exit 1; }
export PATH="/usr/local/sbin:/usr/local/bin:${PATH}"

## install k3s
K3S_DISABLE="${K3S_DISABLE:-servicelb,traefik}"
export INSTALL_K3S_CHANNEL_URL="https://update.k3s.io/v1-release/channels"
export INSTALL_K3S_CHANNEL="stable"
echo "### installing k3s --disable=${K3S_DISABLE} ###"
curl -fsSL https://get.k3s.io | sh -s - --disable="${K3S_DISABLE}"

## kubeconfig
echo "### sync kubeconfig ###"
while [ ! -f /etc/rancher/k3s/k3s.yaml ]; do
	echo "kubeconfig [ /etc/rancher/k3s/k3s.yaml ] not exist yet"
	sleep 3
done
echo "kubeconfig [ /etc/rancher/k3s/k3s.yaml ] exists!"
mkdir -p /root/.kube
cp /etc/rancher/k3s/k3s.yaml /root/.kube/config

## kubectl
sleep 3
kubectl get nodes
