#!/bin/bash

## k3s env vars
#export K3S_KUBECONFIG_MODE="644"
#export INSTALL_K3S_EXEC=" --no-deploy servicelb --no-deploy traefik"

## install k3s
export INSTALL_K3S_VERSION="v1.30.2+k3s2"
curl -fsSL https://get.k3s.io | sh -s - --disable=servicelb,traefik

## kubeconfig
echo "### sync kubeconfig ###"
while [ -f /etc/rancher/k3s/k3s.yaml ]; do
	echo "kubeconfig [ /etc/rancher/k3s/k3s.yaml ] not exist yet"
	sleep 3
done
echo "kubeconfig [ /etc/rancher/k3s/k3s.yaml ] exists!"
mkdir -p /root/.kube
cp /etc/rancher/k3s/k3s.yaml /root/.kube/config

## kubectl
sleep 3
kubectl get nodes
kubectl get pods -A
