apiVersion: v1
kind: Service
metadata:
  name: vip-frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: host
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: acmefit
    service: frontend
  type: LoadBalancer
