apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedoom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: akoapps/kubedoom
    repoURL: 'https://github.com/apnex/labops'
    targetRevision: HEAD
  destination:
    name: cluster-tenant1
    namespace: kubedoom
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
