#!/bin/bash

NEWPASSWORD=${1} ## from stdin
if [[ -z ${NEWPASSWORD} ]]; then
	NEWPASSWORD="VMware1!" ## default password
fi

## patch argo secret
NEWSECRET=$(argocd account bcrypt --password ${NEWPASSWORD})
echo "Reset password to [ ${NEWPASSWORD} ] : [ ${NEWSECRET} ]"
kubectl patch secret -n argocd argocd-secret \
-p '{
	"stringData": {
		"admin.password": "'"${NEWSECRET}"'"
	}
}'

# verify secret
#kubectl get secret -n argocd argocd-secret -o json | \
#  jq '.data|to_entries|map({key, value:.value|@base64d})|from_entries'
