apiVersion: v1
kind: LimitRange
metadata:
  name: ns-limit-range
spec:
  limits:
  - default:
      cpu: 300m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
