#!/bin/bash

### references
#https://medium.com/titansoft-engineering/kubernetes-cluster-wide-access-to-private-container-registry-with-imagepullsecret-patcher-b8b8fb79f7e5
#https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials

## login interactively
docker login

echo "Create new secret [ docker-login ] with credentials at [ /root/.docker/config.json ]"
## perform kubectl healthcheck
## perform a check if config.json exists
kubectl create secret generic docker-login \
	--from-file=.dockerconfigjson=/root/.docker/config.json \
	--type=kubernetes.io/dockerconfigjson

echo "Updated serviceaccount [ default ] for namespace [ default ] to use [ docker-login ]"
kubectl patch serviceaccount default \
-p '{
	"imagePullSecrets": [
		{
			"name": "docker-login"
		}
	]
}'

## delete all failed pods in default namespace?
