apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: acmefit
    service: frontend
spec:
  ports:
    - name: http-frontend
      protocol: TCP
      port: 3000
  selector:
    app: acmefit
    service: frontend
