apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: labops-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labops-rbac
subjects:
- kind: ServiceAccount
  name: labops-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: labops-role
  apiGroup: rbac.authorization.k8s.io
