#!/bin/bash
# for a given deployment, checks that all replicas are in READY state
# returns null

## defaults
VAR_SLEEP=5
if [[ -n $1 ]]; then
	RESOURCE=$1
fi
if [[ -n $2 ]]; then
	NAMESPACE=$2
fi

function getDeploymentReady {
	local JSON=$(kubectl -n ${NAMESPACE} get deployment ${RESOURCE} -o json)
	read -r -d '' FILTER1 <<-'EOF'
		.status.readyReplicas // empty
	EOF
	local READYREPLICAS=$(echo ${JSON} | jq -r "${FILTER1}")
	read -r -d '' FILTER2 <<-'EOF'
		.status.replicas // empty
	EOF
	local REPLICAS=$(echo ${JSON} | jq -r "${FILTER2}")
	local STATUS="${READYREPLICAS} ${REPLICAS}"

	# print X Y
	printf "%s" "${STATUS}"
}

if [[ -n ${RESOURCE} ]]; then
	ALIVE=0
	while [[ $ALIVE == 0 ]]; do
		ARRSTATUS=($(getDeploymentReady "${RESOURCE}" "${NAMESPACE}"))
		READY=${ARRSTATUS[1]}
		TARGET=${ARRSTATUS[0]}

		## check alive
		if [[ -n ${READY} && -n ${TARGET} ]]; then
			if [[ ${READY} -eq ${TARGET} ]]; then
				ALIVE=1
				break
			fi
		fi

		## normalise values
		if [[ -z ${READY} ]]; then
			READY="0"
		fi
		if [[ -z ${TARGET} ]]; then
			TARGET="0"
		fi
		printf "%s\n" "[ K8S/DEPLOYMENT-READY ] REPLICAS [ ${NAMESPACE}/${RESOURCE}:${READY}/${TARGET} ] waiting for RESOURCE.. sleep ${VAR_SLEEP}" 1>&2
		sleep ${VAR_SLEEP}
	done
	printf "%s\n" "[ K8S/DEPLOYMENT-READY ] REPLICAS [ ${NAMESPACE}/${RESOURCE}:${READY}/${TARGET} ] is ALIVE !!" 1>&2
else
	printf "%s\n" "[ K8S/DEPLOYMENT-READY ] ERROR: No DEPLOYMENT defined" 1>&2
fi
