#!/bin/bash
## kubectl healthcheck
export KUBECONFIG=/root/.kube/config
ls -la ${KUBECONFIG}
HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
while [[ -z ${HEALTHY} ]]; do
	echo "socket [ localhost:6443 ] api [ no response ]"
	sleep 10
	HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
	echo "BEFORE TEST: ${HEALTHY}"
	kubectl -n kube-system get pods
	echo "AFTER TEST: ${HEALTHY}"
done
echo "socket [ localhost:6443 ] api [ healthy ]"

## commence
mkdir -p /opt/local-path-provisioner
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

read -r -d '' LOCALSTORAGE <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
EOF

printf "${LOCALSTORAGE}" | kubectl apply -f -
