apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: esx15
spec:
  virtualhost:
    fqdn: esx15.lab01.one
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: esx15
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: esx15
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: esx15
subsets:
  - addresses:
      - ip: 172.16.10.115
    ports:
      - port: 443
