---
apiVersion: v1
kind: Service
metadata:
  name: vip-windows-desktop
  annotations:
    metallb.universe.tf/allow-shared-ip: host
spec:
  ports:
    - port: 3389
      targetPort: 3389
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vip-windows-desktop
subsets:
  - addresses:
      - ip: 192.168.1.68
    ports:
      - port: 3389
