apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: supervisor
spec:
  virtualhost:
    fqdn: supervisor.lab01.one
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: supervisor
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: supervisor
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: supervisor
subsets:
  - addresses:
      - ip: 172.31.0.1
    ports:
      - port: 443
