---
apiVersion: v1
kind: Service
metadata:
  name: vip-vcenter-admin
  annotations:
    metallb.universe.tf/allow-shared-ip: host
spec:
  ports:
    - port: 5480
      targetPort: 5480
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vip-vcenter-admin
subsets:
  - addresses:
      - ip: 172.16.10.110
    ports:
      - port: 5480
