#!/bin/bash
## kubectl healthcheck
echo "[[ ${KUBECONFIG} ]]"
HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
while [[ -z ${HEALTHY} ]]; do
	echo "socket [ localhost:6443 ] api [ no response ]"
	sleep 10
	HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
done
echo "socket [ localhost:6443 ] api [ healthy ]"

## install metallb
# https://metallb.universe.tf/installation/
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml
