#!/bin/bash

## kubectl healthcheck
echo "[[ ${KUBECONFIG} ]]"
HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
while [ -z "${HEALTHY}" ]; do
	echo "socket [ localhost:6443 ] api [ no response ]"
	sleep 10
	HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
done
echo "socket [ localhost:6443 ] api [ healthy ]"

## healthcheck
METAL_CONTROLLER=$(curl -fsSL https://labops.sh/healthcheck/k8s-deployment-ready | RESOURCE="controller" NAMESPACE="metallb-system" bash -- 2>/dev/stderr)

## determine IPV4 ADDRESS of default route interface
ETH=$(route | grep ^default | sed "s/.* //")
IPADDRESS=$(ip addr show "${ETH}" | grep inet\ | awk '{print $2}' | cut -d/ -f1)

read -r -d '' METALPOOL <<EOF
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: host-pool
  namespace: metallb-system
spec:
  addresses:
  - ${IPADDRESS}/32
EOF

echo "${METALPOOL}"

## apply IPAddressPool
printf "${METALPOOL}" | kubectl apply -f -
