#!/bin/bash
## kubectl healthcheck
echo "[[ ${KUBECONFIG} ]]"
HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
while [[ -z ${HEALTHY} ]]; do
	echo "socket [ localhost:6443 ] api [ no response ]"
	sleep 10
	HEALTHY=$(kubectl -n kube-system get pods 2>/dev/null)
done
echo "socket [ localhost:6443 ] api [ healthy ]"

## determine IPV4 ADDRESS of default route interface
ETH=$(route | grep ^default | sed "s/.* //")
IPADDRESS=$(ip addr show "${ETH}" | grep inet\ | awk '{print $2}' | cut -d/ -f1)

read -r -d '' METALPOOL <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${IPADDRESS}/32
EOF

echo "${METALPOOL}"

## apply and restart metallb pods to force update existing service IPs
printf "${METALPOOL}" | kubectl apply -f -
kubectl -n metallb-system delete pods --all
