apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: index
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'https://github.com/apnex/labops'
    targetRevision: HEAD
  project: default
