#!/bin/bash
# https://argoproj.github.io/argo-cd/getting_started/

kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
kubectl apply -n argocd -f https://labops.sh/argo/app.index.yaml
