apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/apnex/labops
        revision: HEAD
        files:
          - path: argo/services.yaml
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      source:
        repoURL: '{{ .repoURL }}'
        targetRevision: '{{ .revision }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
  templatePatch: |
    spec:
      source:
        {{- if eq .type "helm" }}
        chart: {{ .chart | quote }}
        {{- if .values }}
        helm:
          valuesObject: {{ .values | toJson }}
        {{- end }}
        {{- else }}
        path: {{ .gitPath | quote }}
        {{- end }}
