#!/bin/bash

NEWPASSWORD=${1} ## from stdin
if [[ -z ${NEWPASSWORD} ]]; then
	NEWPASSWORD="VMware1!" ## default password
fi

## install bcrypt
yum install -y unzip
curl -sLO https://github.com/bitnami/bcrypt-cli/releases/download/v1.0/bcrypt-linux-x64.zip
unzip bcrypt-linux-x64.zip
mv bcrypt-linux-x64 /usr/bin/bcrypt
rm bcrypt-linux-x64.zip
chmod 755 /usr/bin/bcrypt

## patch argo secret
NEWSECRET=$(echo -n "${NEWPASSWORD}" | bcrypt | tr -d ':\n')
echo "Reset password to [ ${NEWPASSWORD} ] : [ ${NEWSECRET} ]"
kubectl patch secret -n argocd argocd-secret \
-p '{
	"stringData": {
		"admin.password": "'"${NEWSECRET}"'"
	}
}'

# verify
#kubectl get secret -n argocd argocd-secret -o json | \
#  jq '.data|to_entries|map({key, value:.value|@base64d})|from_entries'
